version: '3.8'

services:
  node-app:
    image: node:20
    container_name: my-node-app
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run start"
